### ISSUE TITLE
Add at least one other maintainer (bus-factor)

### ISSUE THREAD

**Issue by kinow** [conda-forge/graphql-ws-feedstock#2]
@hjoliver, @dwsutherland, @oliver-sanders, any volunteers?

At the moment I am the only one set as maintainer of the conda package. It is a dependency of our Cylc UI Server feedstock.

I pinged the maintainers of the OSS package, but they were busy with other tasks and haven't volunteered to maintain the feedstock (yet, I expect them to join us later).

**Comment by hjoliver** [comment]
I volunteer :raised_hand_with_fingers_splayed:
